# Generated by Django 4.0.4 on 2022-04-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('city_location', models.CharField(choices=[], default='not specified', max_length=25)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('square', models.PositiveIntegerField()),
                ('amount_of_beds', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExcursionVisiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Accomodation',
        ),
        migrations.AddField(
            model_name='user',
            name='visited_excursions',
            field=models.ManyToManyField(through='agency.ExcursionVisiting', to='agency.excursion'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='city',
            field=models.CharField(choices=[('London', 'London'), ('Paris', 'Paris'), ('Berlin', 'Berlin'), ('Lisbon', 'Lisbon')], default='not specified', max_length=25),
        ),
        migrations.AddField(
            model_name='excursionvisiting',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.excursion'),
        ),
        migrations.AddField(
            model_name='excursionvisiting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.user'),
        ),
    ]
