# Generated by Django 4.0.4 on 2022-04-21 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_accommodation_excursionvisiting_delete_accomodation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='rating',
        ),
        migrations.AlterField(
            model_name='excursionvisiting',
            name='user_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExcursionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.excursion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationVisiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rate', models.FloatField(blank=True, null=True)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.excursion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.user')),
            ],
        ),
    ]
