# Generated by Django 4.0.4 on 2022-05-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_remove_accommodation_rating_remove_excursion_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'ordering': ['-id']},
        ),
    ]
