# Generated by Django 4.0.4 on 2022-05-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_alter_excursionvisiting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursionvisiting',
            options={'ordering': ['user_rate']},
        ),
    ]
