# Generated by Django 4.0.4 on 2022-05-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_alter_excursionvisiting_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursionvisiting',
            options={'ordering': ['-user_rate']},
        ),
        migrations.AlterField(
            model_name='excursionvisiting',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursions', to='agency.excursion'),
        ),
        migrations.AlterField(
            model_name='excursionvisiting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='agency.user'),
        ),
    ]
