# Generated by Django 3.2.13 on 2022-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_alter_excursionvisiting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
