# Generated by Django 3.2.13 on 2022-05-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='avg_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
